In [1]:
import pandas as pd

Use this notebook to process predictable data

Use a file that can capture all the time keys for the relevant month. In here used 4gtraffic

In [2]:
traffic=pd.read_csv('../data/processed/data_traffic_4g_new.csv')

In [3]:
# traffic = traffic.rename(columns={'total_dl': 'dltrafficvolume(gb)(gb)','total_ul': 'ultrafficvolume(gb)(gb)'})

In [4]:
# traffic=traffic[['site_id','date','hour','dltrafficvolume(gb)(gb)','ultrafficvolume(gb)(gb)']]

In [5]:
# traffic = traffic.rename(columns={'site_id': 'Site_Id'})

In [6]:
# traffic = traffic.rename(columns={'date': 'Date','hour':'Hour'})

In [7]:
traffic

,Unnamed: 0,Site_Id,Time_Key,dltrafficvolume(gb)(gb),ultrafficvolume(gb)(gb)
0,0,AM0004,2022120100,18.7978,1.5376
1,1,AM0004,2022120101,9.9607,0.8118
2,2,AM0004,2022120102,7.1119,0.7663
3,3,AM0004,2022120103,4.0087,0.6552
4,4,AM0004,2022120104,4.7399,0.6803
...,...,...,...,...,...
3431345,3431345,VA5034,2022123119,12.3715,1.5716
3431346,3431346,VA5034,2022123120,12.8263,1.9184
3431347,3431347,VA5034,2022123121,12.7316,1.6603
3431348,3431348,VA5034,2022123122,11.7411,1.3846
3431349,3431349,VA5034,2022123123,10.0833,1.1445

In [46]:
# # traffic1 = traffic[traffic.Site_Id == '0']
# # traffic1
# # row = traffic[traffic['Site_Id'] == 'GMO460']
# # row

# if 'Site_Id' in traffic.columns:
#     row = traffic[traffic['Site_Id'] == 'GMO460']
#     if row.empty:
#         print('Site_Id GMO460 is not available in the dataframe')
#     else:
#         print('The relevant row:')
#         print(row)
# else:
#     print('Site_Id column is not in the dataframe')

In [47]:
#FOUND SOME IDS WITH '0'

# traffic = traffic[traffic.Site_Id != '0']
# traffic = traffic.groupby(['Site_Id','Date','Hour']).sum()
# traffic=traffic.reset_index()

# check if there are any rows where ids == 0
# any_zero_ids = traffic[traffic['Site_Id'] == '0'].any().any()
# print(any_zero_ids)

In [8]:
traffic['Site_Id'].nunique()

4747

In [9]:
print(traffic.isna().any())

Unnamed: 0                 False
Site_Id                    False
Time_Key                   False
dltrafficvolume(gb)(gb)    False
ultrafficvolume(gb)(gb)    False
dtype: bool

In [50]:
# all_sites_to_be_predicted=pd.read_excel('../data/raw/latest-2022-12/all_sites_to_be_predicted.xlsx')

In [51]:
# all_sites_to_be_predicted

In [52]:
# all_sites_to_be_predicted=all_sites_to_be_predicted[['Site_Id','Router_Count', 'Links_Count', 'High_Pwr_RRU_Count', 'Medium_Pwr_RRU_Count', 'Low_Pwr_RRU_Count','Cabin_Type','Region']]

In [53]:
# all_sites_to_be_predicted=all_sites_to_be_predicted.drop_duplicates(subset="Site_Id")

In [13]:
all_sites_to_be_predicted=pd.read_csv('../data/processed/siteinfo.csv')

In [14]:
# all_sites_to_be_predicted=all_sites_to_be_predicted.drop(['Unnamed: 0'],axis=1)

all_sites_to_be_predicted=all_sites_to_be_predicted.drop(['Unnamed: 0'],axis=1)
all_sites_to_be_predicted

,Site_Id,Router_Count,Links_Count,High_Pwr_RRU_Count,Medium_Pwr_RRU_Count,Low_Pwr_RRU_Count,Cabin_Type,District,Region,Site_Type
0,AM0004,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei
1,AM0005,1.0,1.0,1,3,9,OutdoorBTS,Ampara 2,ESR,Huawei
2,AM0008,1.0,5.0,2,4,14,IndoorBTS,Ampara 1,ESR,Huawei
3,AM0010,1.0,NaN,3,4,12,IndoorBTS,Ampara 1,ESR,Huawei
4,AM0011,2.0,3.0,3,4,11,IndoorBTS,Ampara 1,ESR,Huawei
...,...,...,...,...,...,...,...,...,...,...
4790,VA5016,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei
4791,VA5020,0.0,0.0,0,4,0,Lamp Pole,Vavuniya,NTR,Huawei
4792,VA5021,0.0,0.0,0,4,0,Lamp Pole,Vavuniya,NTR,Huawei
4793,VA5033,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei
4794,VA5034,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei

In [15]:
merge = pd.merge(traffic,all_sites_to_be_predicted,on='Site_Id')

In [17]:
merge
# merge=merge.drop(['Unnamed: 0_x','Unnamed: 0_y'],axis=1)
# merge

,Unnamed: 0,Site_Id,Time_Key,dltrafficvolume(gb)(gb),ultrafficvolume(gb)(gb),Router_Count,Links_Count,High_Pwr_RRU_Count,Medium_Pwr_RRU_Count,Low_Pwr_RRU_Count,Cabin_Type,District,Region,Site_Type
0,0,AM0004,2022120100,18.7978,1.5376,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei
1,1,AM0004,2022120101,9.9607,0.8118,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei
2,2,AM0004,2022120102,7.1119,0.7663,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei
3,3,AM0004,2022120103,4.0087,0.6552,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei
4,4,AM0004,2022120104,4.7399,0.6803,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415141,3431345,VA5034,2022123119,12.3715,1.5716,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei
3415142,3431346,VA5034,2022123120,12.8263,1.9184,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei
3415143,3431347,VA5034,2022123121,12.7316,1.6603,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei
3415144,3431348,VA5034,2022123122,11.7411,1.3846,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei
3415145,3431349,VA5034,2022123123,10.0833,1.1445,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei

In [18]:
# merge['Date'] = pd.to_datetime(merge['Date'])
# merge['day_of_week'] = merge['Date'].dt.dayofweek


merge['DT'] = pd.to_datetime(merge['Time_Key'], format='%Y%m%d%H')
merge['day_of_week'] = merge['DT'].dt.strftime('%w')
merge['hour'] = merge['DT'].dt.strftime('%H')

In [19]:
merge

,Unnamed: 0,Site_Id,Time_Key,dltrafficvolume(gb)(gb),ultrafficvolume(gb)(gb),Router_Count,Links_Count,High_Pwr_RRU_Count,Medium_Pwr_RRU_Count,Low_Pwr_RRU_Count,Cabin_Type,District,Region,Site_Type,DT,day_of_week,hour
0,0,AM0004,2022120100,18.7978,1.5376,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei,2022-12-01 00:00:00,4,00
1,1,AM0004,2022120101,9.9607,0.8118,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei,2022-12-01 01:00:00,4,01
2,2,AM0004,2022120102,7.1119,0.7663,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei,2022-12-01 02:00:00,4,02
3,3,AM0004,2022120103,4.0087,0.6552,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei,2022-12-01 03:00:00,4,03
4,4,AM0004,2022120104,4.7399,0.6803,1.0,1.0,0,2,10,IndoorBTS,Ampara 1,ESR,Huawei,2022-12-01 04:00:00,4,04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415141,3431345,VA5034,2022123119,12.3715,1.5716,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei,2022-12-31 19:00:00,6,19
3415142,3431346,VA5034,2022123120,12.8263,1.9184,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei,2022-12-31 20:00:00,6,20
3415143,3431347,VA5034,2022123121,12.7316,1.6603,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei,2022-12-31 21:00:00,6,21
3415144,3431348,VA5034,2022123122,11.7411,1.3846,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei,2022-12-31 22:00:00,6,22
3415145,3431349,VA5034,2022123123,10.0833,1.1445,0.0,0.0,0,3,0,Lamp Pole,Vavuniya,NTR,Huawei,2022-12-31 23:00:00,6,23

In [20]:
# print(december_predictable_data.isna().any())
def cabintype_correction(inpt):
    if inpt == 'Lamp pole' or inpt == 'Lamp Pole' or inpt == 'lamp Pole':
        return 'Lamp Pole'
    else:
        return inpt

In [21]:
zerofill_columns = ['Medium_Pwr_RRU_Count','Low_Pwr_RRU_Count','High_Pwr_RRU_Count', 'Router_Count', 'Links_Count']

for col in zerofill_columns:
    merge[col] = merge[col].fillna(0)

merge.count()

Unnamed: 0                 3415146
Site_Id                    3415146
Time_Key                   3415146
dltrafficvolume(gb)(gb)    3415146
ultrafficvolume(gb)(gb)    3415146
Router_Count               3415146
Links_Count                3415146
High_Pwr_RRU_Count         3415146
Medium_Pwr_RRU_Count       3415146
Low_Pwr_RRU_Count          3415146
Cabin_Type                 3389936
District                   3405553
Region                     3387625
Site_Type                  3400889
DT                         3415146
day_of_week                3415146
hour                       3415146
dtype: int64

In [22]:
merge['Cabin_Type'] = merge['Cabin_Type'].apply(cabintype_correction)
merge["Cabin_Type"] = merge["Cabin_Type"].replace("\s+$", "", regex=True)
merge = merge.dropna()
merge = merge[merge["Region"].apply(lambda x: not isinstance(x, int))]

In [23]:
merge = merge[merge.Cabin_Type != 'Lamp Pole']

In [24]:
merge['District'] = merge['Site_Id'].str[:2]

In [25]:
ids_to_remove = ['AM0008','AM0035','AM0088','AM0122','AM0142','AN0002','AN0013','AN0015','AN0016','AN0095','AN0222','BA0013','BA0023','BA0029','BA0042','BA0066','BA0084','BA0114','BD0001','BD0010','BD0029','BD0044','BD0120','CM0009','CM0053','CM0054','CM0056','CM0121','CM0175','CM0220','CM0238','CM0249','CM0256','CM0260','CM0312','CM0339','CM0351','CM0386','CM0417','CM0450','CM0463','CM0502','CM0590','CM0623','CM0667','CM0742','CM0823','CM0827','CM0967','CM1029','CM1034','CM1035','CM1077','CM1168','CM1222','CM1226','CM1338','CM1463','GA0006','GA0020','GA0030','GA0041','GA0054','GA0097','GA0105','GA0110','GA0182','GM0052','GM0084','GM0094']

# Select only the rows that do not have any of the IDs you want to remove
merge = merge[~merge['Site_Id'].isin(ids_to_remove)]

In [ ]:
# twogdata=twogdata.drop('Unnamed: 0',axis=1)

In [26]:
merge.to_csv('../data/processed/december_predictable_data.csv')

In [27]:
merge.isna().any()

Unnamed: 0                 False
Site_Id                    False
Time_Key                   False
dltrafficvolume(gb)(gb)    False
ultrafficvolume(gb)(gb)    False
Router_Count               False
Links_Count                False
High_Pwr_RRU_Count         False
Medium_Pwr_RRU_Count       False
Low_Pwr_RRU_Count          False
Cabin_Type                 False
District                   False
Region                     False
Site_Type                  False
DT                         False
day_of_week                False
hour                       False
dtype: bool

### MERGE 2G DATA

In [13]:
december_predictable_data=pd.read_csv('../data/processed/december_predictable_data.csv')
twogdata=pd.read_csv('../data/processed/twogdata.csv')
# cooling=pd.read_csv('../data/processed/cooling.csv')

In [32]:

# id_counts = twogdata[twogdata['Site_Id'] == 'RA0120']['Site_Id'].value_counts()
# id_counts
twogdata = twogdata.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1)

In [33]:
december_predictable_data=december_predictable_data.drop('Unnamed: 0',axis=1)
# coolingcooling.drop('Unnamed: 0',axis=1)

In [34]:
# december_predictable_data['Date'] = pd.to_datetime(december_predictable_data['Date'], format='%Y-%m-%d')
# december_predictable_data['Time_Key'] = december_predictable_data.apply(lambda row: int(row['Date'].strftime('%Y%m%d')+ str(row['Hour']).zfill(2)), axis=1)

In [35]:
december_predictable_data=december_predictable_data.drop(['DT'],axis=1)

In [37]:
december_predictable_data=december_predictable_data.drop('Unnamed: 0.1',axis=1)
december_predictable_data

,Site_Id,Time_Key,dltrafficvolume(gb)(gb),ultrafficvolume(gb)(gb),Router_Count,Links_Count,High_Pwr_RRU_Count,Medium_Pwr_RRU_Count,Low_Pwr_RRU_Count,Cabin_Type,District,Region,Site_Type,day_of_week,hour
0,AM0004,2022120100,18.7978,1.5376,1.0,1.0,0,2,10,IndoorBTS,AM,ESR,Huawei,4,0
1,AM0004,2022120101,9.9607,0.8118,1.0,1.0,0,2,10,IndoorBTS,AM,ESR,Huawei,4,1
2,AM0004,2022120102,7.1119,0.7663,1.0,1.0,0,2,10,IndoorBTS,AM,ESR,Huawei,4,2
3,AM0004,2022120103,4.0087,0.6552,1.0,1.0,0,2,10,IndoorBTS,AM,ESR,Huawei,4,3
4,AM0004,2022120104,4.7399,0.6803,1.0,1.0,0,2,10,IndoorBTS,AM,ESR,Huawei,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2969319,VA0123,2022123119,13.2570,1.9353,0.0,0.0,0,2,2,OutdoorBTS,VA,NTR,Huawei,6,19
2969320,VA0123,2022123120,17.2063,3.0474,0.0,0.0,0,2,2,OutdoorBTS,VA,NTR,Huawei,6,20
2969321,VA0123,2022123121,20.1698,3.1637,0.0,0.0,0,2,2,OutdoorBTS,VA,NTR,Huawei,6,21
2969322,VA0123,2022123122,19.8310,2.9433,0.0,0.0,0,2,2,OutdoorBTS,VA,NTR,Huawei,6,22
2969323,VA0123,2022123123,14.5275,2.4763,0.0,0.0,0,2,2,OutdoorBTS,VA,NTR,Huawei,6,23

In [38]:
m=pd.merge(december_predictable_data,twogdata,on=['Site_Id','Time_Key'])

In [45]:
m.to_csv('../data/processed/december_predictable_data.csv')

#FINAL DATASET FOR PREDICTION DECEMBER

In [6]:
# f = m[m['Time_Key'] == 2022122712]
# f
# ids=['RA0120', 'CM0534', 'CM0257', 'BD0061', 'GM0411', 'KA0070', 'BD0014', 'CM0618', 'KL0179', 'GM0359', 'HA0028', 'CM0615']
# id_counts = m[m['Site_Id'].isin(ids)]['Site_Id'].value_counts()
# id_counts